name: Create manual release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        type: string
      release_title:
        description: 'Release Title'
        required: true
        type: string
      is_pre_release:
        description: 'Is Pre-Release?'
        required: false
        type: boolean
      is_draft:
        description: 'Is Draft?'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup and verify build passes tests
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{hashFiles('package-lock.json')}}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm test

      # Bump version and tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          release_branches: release
          custom_tag: ${{github.event.inputs.release_version}}
          tag_prefix: ''

      # Build and add artifacts to release
      - name: Build dist folder
        run: npm run build

      - name: Substitute module.json values based on tag name
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: './dist/module.json'
        env:
          version: ${{github.event.inputs.release_version}}
          url: https://github.com/${{github.repository}}
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.inputs.release_version}}/module-profiles.zip

      - name: Create release module .zip file
        run: cd dist && zip -r ../module-profiles.zip .

      - name: Create release with files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{github.event.inputs.release_title}}
          draft: ${{github.event.inputs.is_draft}}
          prerelease: ${{github.event.inputs.is_pre_release}}
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: './dist/module.json, ./module-profiles.zip'
          tag: ${{github.event.inputs.release_version}}
          body: ${{steps.tag_version.outputs.changelog}}
